version: "3"

services:
    mq-asd:
        image: "rabbitmq:3-management"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - asd-net

    mongo-asd:
        image: 'mongo'
        ports:
            - '27017:27017'
        networks:
            - asd-net

    base-asd:
        build:
            context: "./asd"
            dockerfile: Dockerfile

        image: asd-base:latest
          

    server-asd: 
        build:
            context: "./asd"
            dockerfile: "./server/Dockerfile"
        ports: 
            - 5000:5000
        command: ["run_server", "--config_path", "/config.ini"]
        depends_on:
            - mq-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data

    api-asd: 
        build:
            context: "./asd"
            dockerfile: "./api/Dockerfile"
        ports: 
            - 8000:8000
        command: ["run", "--config_path", "/config.ini"]
        depends_on:
            - mongo-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data

    pose-asd:
        build:
            context: "./asd"
            dockerfile: "./workers/Dockerfile"
        command: ["--w", "pose", "--config_path", "/config.ini"]
        depends_on:
            - mq-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data
        restart: on-failure

    color_image-asd:
        build:
            context: "./asd"
            dockerfile: "./workers/Dockerfile"
        command: ["--w", "color_image", "--config_path", "/config.ini"]
        depends_on:
            - mq-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data
        restart: on-failure

    
    depth_image-asd:
        build:
            context: "./asd"
            dockerfile: "./workers/Dockerfile"
        command: ["--w", "depth_image", "--config_path", "/config.ini"]
        depends_on:
            - mq-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data
        restart: on-failure

    feelings-asd:
        build:
            context: "./asd"
            dockerfile: "./workers/Dockerfile"
        command: ["--w", "feelings", "--config_path", "/config.ini"]
        depends_on:
            - mq-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data
        restart: on-failure
    
    users-asd:
        build:
            context: "./asd"
            dockerfile: "./workers/Dockerfile"
        command: ["--w", "users", "--config_path", "/config.ini"]
        depends_on:
            - mq-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data
        restart: on-failure

    db-asd:
        build:
            context: "./asd"
            dockerfile: "./dbclient/Dockerfile"
        command: ["run", "--config_path", "/config.ini"]
        depends_on:
            - mq-asd
            - mongo-asd
            - base-asd
        networks:
            - asd-net
        volumes: 
            - ./asd/data:/data
        restart: on-failure

networks:
    asd-net: